# Generated by Django 5.1.5 on 2025-02-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=500)),
                ('price_without_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('delivery_type', models.CharField(max_length=100)),
                ('free_shipping', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product_offers',
            },
        ),
    ]
