# Generated by Django 5.1.5 on 2025-02-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='parcelamento',
            field=models.CharField(max_length=300),
        ),
    ]
