# Generated by Django 5.1.5 on 2025-02-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_alter_produto_parcelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='produto',
            name='parcelamento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_entrega',
            field=models.CharField(max_length=100),
        ),
    ]
